# Generated by Django 4.1.2 on 2022-10-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=20)),
                ('addr_city', models.CharField(max_length=30)),
            ],
        ),
    ]
