# Generated by Django 4.1.2 on 2022-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
